# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content
  title: Ryusuke Miyazaki's page


ja:
  locale: ja-jp
  contentDir: content
  title: 宮崎竜輔's page

ko:
  locale: ko-kr
  contentDir: content
  # menu:
  #   main:
  #     - name: 日本語
  #       url: '#about'
  #       weight: 1
# Uncomment the lines below to configure your website in a second language.
#zh:
#  locale: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
