hugoblox:
  schema: "2.0"
  identity:
    name: Ryusuke Miyazaki - These pages are under constraction
    type: person
    tagline: Doctorial Student
    description: |-
      Ryusuke Miyazaki is a Doctorial Student in Institute of Science Tokyo, Japan.
      He belongs to TAC-MI (Graduate Major in Materials and Information Sciences
      Academ)
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © 2026 Ryusuke Miyazaki
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
    citations:
      style: ieee
  search:
    enable: true
